@baseUrl = http://localhost:8000/api/v1/todos

### List Todos
GET {{baseUrl}}
Content-Type: application/json

### Create Todo
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "Buy groceries",
  "description": "Milk, Cheese, Pizza, Fruit",
  "completed": false
}

### Get Todo
GET {{baseUrl}}/1
Content-Type: application/json

### Update Todo
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "title": "Buy groceries and snacks",
  "completed": true
}

### Delete Todo
DELETE {{baseUrl}}/1
Content-Type: application/json
