pipeline {
    agent {
        docker {
            image 'python:3.12-slim'
            args '-u root'
        }
    }

    environment {
        // Usamos la ruta absoluta al HOME del usuario root en el contenedor
        PATH = "/root/.local/bin:${env.PATH}"
    }

    stage('Checkout Project') {
            steps {
                echo 'Descargando código desde Git...'
                // Descarga el código del repositorio configurado en Jenkins
                checkout scm
            }
        }

    stages {
        stage('Setup Environment') {
            steps {
                script {
                    sh 'apt-get update && apt-get install -y curl'
                    // Instalamos uv
                    sh 'curl -LsSf https://astral.sh/uv/install.sh | sh'
                    
                    // LLAMADA CLAVE: Usamos la ruta completa para el primer chequeo
                    // Esto evita el "not found" si el PATH no se refrescó a tiempo
                    sh '/root/.local/bin/uv --version'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                // Aquí ya debería reconocer 'uv' por el bloque environment
                // Si vuelve a fallar, usa la ruta completa: /root/.local/bin/uv sync
                sh '/root/.local/bin/uv sync'
            }
        }

        stage('Lint & Static Analysis') {
            steps {
                sh '/root/.local/bin/uv run ruff check .'
            }
        }

        stage('Run Tests') {
            steps {
                sh '/root/.local/bin/uv run pytest'
            }
        }
    }

    post {
        failure {
            echo 'Error detectado. Si el error es "uv: not found", intenta reemplazar "uv" por "/root/.local/bin/uv" en los comandos sh.'
        }
        always {
            echo 'Finalizando el pipeline...'
        }
        success {
            echo '¡El despliegue/test ha sido exitoso!'
        }
    }
}